apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: "/data"
      name: glusterfs-volume
  volumes:
  - name: glusterfs-volume
    persistentVolumeClaim:
      claimName: glusterfs-pvc
