apiVersion: v1
kind: Pod
metadata:
  name: training-pod
spec:
  containers:
  - name: training-container
    image: leifhuender/distributed_gpu_test:latest
    resources:
      requests:
        memory: "14Gi"
        cpu: "10"
      limits:
        memory: "14Gi"
        cpu: "10"

    env:
      - name: MASTER_ADDR
        value: "192.168.50.132"
      - name: MASTER_PORT
        value: "53394"
    volumeMounts:
    - name: nfs-storage
      mountPath: /data
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc


